apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: front-back-db
spec:
  environments:
    stage:
      defaultNamespace: stage
      server: https://127.0.0.1:6443
      excludes:
        - endpoint
    prod:
      defaultNamespace: prod
      server: https://127.0.0.1:6443
  vars: {}