---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "front-back-db.fullname" . }}-back
  labels:
    {{- include "front-back-db.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount.backend }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "front-back-db.selectorLabels" . | nindent 6 }}
      {{- toYaml .Values.labels.backend | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "front-back-db.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.labels.backend | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "front-back-db.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - name: backend
              containerPort: {{ .Values.service.backend.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /news
              port: {{ .Values.endpoint.backend }}
          readinessProbe:
            httpGet:
              path: /news
              port: {{ .Values.endpoint.backend }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env.backend | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "front-back-db.fullname" . }}-back
  labels:
    {{- include "front-back-db.labels" . | nindent 4 }}
    {{- toYaml .Values.labels.backend | nindent 4 }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.targetPort }}
      protocol: TCP
      name: backend
  selector:
    {{- include "front-back-db.selectorLabels" . | nindent 4 }}