apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-01
spec:
  selector:
    matchLabels:
      app: db
  serviceName: "db-postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: db
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_DB
            value: news