apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-and-back
  labels:
    app: front-back
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-back
  template:
    metadata:
      labels:
        app: front-back
    spec:
      containers:
      - name: frontend
        image: la3ft/netology-front
        ports:
        - containerPort: 80
      - name: backend
        image: la3ft/netology-back
        ports:
        - containerPort: 9000